Expose timeout for lock via environment variable configuration
resque/resque-scheduler pull request #786
Opened 2023-12-19 19:12 UTC by pmm4654

2024-04-25 22:23 UTC, learoyklinginsmith commented
@PatrickTulskie any chance we could get some eyes on this change? 🙏

2024-05-08 14:52 UTC, PatrickTulskie requested changes
Overall good. I'd just like to set the env stuff the way it was instead of the meta programming approach. Calling `send` usually winds up causing a lot more scrutiny.

2024-05-08 14:52 UTC, PatrickTulskie commented on lib/resque/scheduler/env.rb
> -          c.logformat = options[:logformat] if options.key?(:logformat)
Can we just leave this and add the new timeout option?

2024-11-27 19:22 UTC, pmm4654 commented
@PatrickTulskie Hey there! I'm just nudging this PR after I made the changes you requested.

2024-12-29 19:01 UTC, PatrickTulskie approved these changes

2024-12-29 19:01 UTC, merged